
export const TYPES = {
    READ_STATE_PRODUCTS: "READ_STATE_PRODUCTS",
    READ_STATE_CART: "READ_STATE_CART",
    ADD_TO_CART: "ADD_TO_CART",
    EDIT_QUANTITY: "EDIT_QUANTITY",
    REMOVE_ONE_FROM_CART: "REMOVE_ONE_FROM_CART",
    REMOVE_ALL_FROM_CART: "REMOVE_ALL_FROM_CART",
    CLEAR_CART: "CLEAR_CART",
}

